# MOSQUITTO CONFIG - FanJet BMS
# Mosquitto 2.1.x compatible

# MQTT TCP Listener
listener 1883
allow_anonymous true

# WebSocket Listener
listener 9001
protocol websockets

# Logging
log_dest file C:\Program Files\mosquitto\log\mosquitto.log
log_type all
log_timestamp true
