# Generated by Django 6.0.4 on 2026-04-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_id', models.CharField(max_length=20, unique=True, verbose_name='Mã quạt')),
                ('name', models.CharField(max_length=100, verbose_name='Tên quạt')),
                ('zone', models.CharField(choices=[('B1', 'Tầng hầm 1 (B1)'), ('B2', 'Tầng hầm 2 (B2)')], default='B1', max_length=2, verbose_name='Khu vực')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Vị trí')),
                ('topic', models.CharField(blank=True, help_text='Để trống sẽ tự sinh từ tiền tố + fan_id', max_length=255, verbose_name='MQTT Topic')),
                ('temp_warn', models.FloatField(default=35.0, verbose_name='Ngưỡng cảnh báo nhiệt độ (°C)')),
                ('temp_alarm', models.FloatField(default=40.0, verbose_name='Ngưỡng báo động nhiệt độ (°C)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quạt',
                'verbose_name_plural': 'Danh sách quạt',
                'ordering': ['zone', 'fan_id'],
            },
        ),
        migrations.CreateModel(
            name='MQTTConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_host', models.CharField(default='localhost', max_length=255, verbose_name='Địa chỉ Broker')),
                ('broker_port', models.PositiveIntegerField(default=1883, verbose_name='Cổng')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Tên đăng nhập')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Mật khẩu')),
                ('client_id', models.CharField(default='fanjet-web-01', max_length=255, verbose_name='Client ID')),
                ('topic_prefix', models.CharField(default='fanjet/basement', max_length=255, verbose_name='Tiền tố Topic')),
                ('qos', models.PositiveSmallIntegerField(choices=[(0, 'QoS 0 – At most once'), (1, 'QoS 1 – At least once'), (2, 'QoS 2 – Exactly once')], default=1, verbose_name='Mức QoS')),
                ('keep_alive', models.PositiveIntegerField(default=60, verbose_name='Keep Alive (giây)')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Dùng TLS/SSL')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
            ],
            options={
                'verbose_name': 'Cấu hình MQTT',
                'verbose_name_plural': 'Cấu hình MQTT',
            },
        ),
    ]
