# Generated by Django 6.0.4 on 2026-04-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COSpeedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_ppm', models.FloatField(verbose_name='Nồng độ CO (ppm)')),
                ('speed_pct', models.IntegerField(verbose_name='Tốc độ quạt (%)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Điểm CO-Speed',
                'ordering': ['order', 'co_ppm'],
            },
        ),
        migrations.CreateModel(
            name='FanTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('co_ppm', models.FloatField()),
                ('speed_pct', models.IntegerField()),
                ('is_tripped', models.BooleanField(default=False)),
                ('mode', models.CharField(default='auto', max_length=10)),
            ],
            options={
                'verbose_name': 'Telemetry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FanUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=20, unique=True, verbose_name='Mã bộ quạt')),
                ('name', models.CharField(max_length=100, verbose_name='Tên bộ quạt')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Vị trí')),
                ('zone', models.CharField(choices=[('B1', 'Tầng hầm 1 (B1)'), ('B2', 'Tầng hầm 2 (B2)')], default='B1', max_length=2, verbose_name='Khu vực')),
                ('mqtt_topic_base', models.CharField(blank=True, max_length=255, verbose_name='MQTT Topic Base')),
                ('control_mode', models.CharField(choices=[('auto', 'Tự động (Auto)'), ('manual', 'Thủ công (Manual)')], default='auto', max_length=10, verbose_name='Chế độ điều khiển')),
                ('manual_speed', models.IntegerField(default=0, verbose_name='Tốc độ thủ công (%)')),
                ('co_warn_ppm', models.FloatField(default=25.0, verbose_name='Ngưỡng cảnh báo CO (ppm)')),
                ('co_alarm_ppm', models.FloatField(default=50.0, verbose_name='Ngưỡng báo động CO (ppm)')),
                ('last_co_ppm', models.FloatField(blank=True, null=True)),
                ('last_speed_pct', models.IntegerField(blank=True, null=True)),
                ('last_tripped', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bộ quạt',
                'verbose_name_plural': 'Danh sách bộ quạt',
                'ordering': ['zone', 'unit_id'],
            },
        ),
        migrations.CreateModel(
            name='OllamaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='http://localhost:11434', max_length=255, verbose_name='Địa chỉ Ollama')),
                ('default_model', models.CharField(default='llama3.2', max_length=100, verbose_name='Model mặc định')),
                ('system_prompt', models.TextField(default='Bạn là trợ lý AI của hệ thống quản lý quạt thông gió tầng hầm FanJet. Trả lời bằng tiếng Việt, ngắn gọn và chính xác. Khi được hỏi về quạt, hãy dựa vào dữ liệu thực tế được cung cấp.', verbose_name='System Prompt')),
            ],
            options={
                'verbose_name': 'Cấu hình Ollama AI',
            },
        ),
        migrations.DeleteModel(
            name='Fan',
        ),
        migrations.AlterModelOptions(
            name='mqttconfig',
            options={'verbose_name': 'Cấu hình MQTT'},
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='qos',
            field=models.PositiveSmallIntegerField(choices=[(0, 'QoS 0'), (1, 'QoS 1'), (2, 'QoS 2')], default=1, verbose_name='Mức QoS'),
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fantelemetry',
            name='fan_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='dashboard.fanunit'),
        ),
        migrations.AddField(
            model_name='cospeedpoint',
            name='fan_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_speed_points', to='dashboard.fanunit'),
        ),
        migrations.AddIndex(
            model_name='fantelemetry',
            index=models.Index(fields=['fan_unit', '-timestamp'], name='dashboard_f_fan_uni_314628_idx'),
        ),
    ]
