# Generated by Django 6.0.4 on 2026-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cospeedpoint_fantelemetry_fanunit_ollamaconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanunit',
            name='zone',
            field=models.CharField(default='B1', help_text='Ví dụ: B1, B2, Tầng 1, Mái...', max_length=50, verbose_name='Khu vực'),
        ),
    ]
