# Generated by Django 6.0.4 on 2026-05-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_fanunit_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mqttconfig',
            options={'verbose_name': 'Cấu hình MQTT Client'},
        ),
        migrations.AddField(
            model_name='mqttconfig',
            name='auto_connect',
            field=models.BooleanField(default=True, help_text='Tự động kết nối MQTT client khi web server khởi động', verbose_name='Tự kết nối khi khởi động'),
        ),
    ]
