# Generated by Django 6.0.4 on 2026-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_mqttconfig_options_mqttconfig_auto_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanunit',
            name='last_carrier',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nhà mạng'),
        ),
        migrations.AddField(
            model_name='fanunit',
            name='last_rssi',
            field=models.IntegerField(blank=True, help_text='Cường độ tín hiệu 4G gateway (dBm)', null=True, verbose_name='RSSI (dBm)'),
        ),
        migrations.AddField(
            model_name='fanunit',
            name='last_signal',
            field=models.CharField(blank=True, default='', help_text='excellent/good/fair/weak/critical/unknown', max_length=20, verbose_name='Chất lượng sóng'),
        ),
    ]
