# Generated by Django 6.0.4 on 2026-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_gateway_signal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanunit',
            name='disconnect_timeout_sec',
            field=models.PositiveIntegerField(default=90, help_text='Nếu không nhận được bản tin sau thời gian này → coi là mất kết nối.', verbose_name='Timeout mất kết nối (giây)'),
        ),
        migrations.AddField(
            model_name='fanunit',
            name='msg_interval_sec',
            field=models.PositiveIntegerField(default=30, help_text='Thời gian giữa 2 bản tin MQTT của quạt (giây). Dùng để đánh giá mất kết nối.', verbose_name='Chu kỳ bản tin (giây)'),
        ),
    ]
