# Generated by Django 6.0.4 on 2026-05-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_connection_timeout_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('boost_per_trip_pct', models.PositiveIntegerField(default=10, help_text='Mỗi 1 quạt bị trip → quạt còn lại tăng thêm X% công suất. Mặc định 10%.', verbose_name='Boost mỗi lần trip (%)')),
                ('max_speed_pct', models.PositiveIntegerField(default=100, help_text='Giới hạn tốc độ tối đa khi áp dụng boost trip. Mặc định 100%.', verbose_name='Tốc độ tối đa khi boost (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('units', models.ManyToManyField(blank=True, help_text='Chọn các quạt thuộc nhóm này.', related_name='fan_groups', to='dashboard.fanunit', verbose_name='Danh sách quạt')),
            ],
            options={
                'verbose_name': 'Nhóm quạt',
                'verbose_name_plural': 'Danh sách nhóm quạt',
                'ordering': ['name'],
            },
        ),
    ]
