# Generated by Django 6.0.4 on 2026-04-14 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosquitto_dir', models.CharField(default='C:\\Program Files\\mosquitto', max_length=500, verbose_name='Thư mục Mosquitto')),
                ('config_path', models.CharField(default='C:\\Program Files\\mosquitto\\mosquitto.conf', max_length=500, verbose_name='File cấu hình')),
                ('password_file', models.CharField(default='C:\\Program Files\\mosquitto\\passwd', max_length=500, verbose_name='File mật khẩu')),
                ('acl_file', models.CharField(default='C:\\Program Files\\mosquitto\\acl', max_length=500, verbose_name='File ACL')),
                ('log_file', models.CharField(default='C:\\Program Files\\mosquitto\\log\\mosquitto.log', max_length=500, verbose_name='File Log')),
                ('port', models.PositiveIntegerField(default=1883, verbose_name='Cổng MQTT')),
                ('ws_port', models.PositiveIntegerField(default=9001, verbose_name='Cổng WebSocket')),
                ('tls_port', models.PositiveIntegerField(default=8883, verbose_name='Cổng TLS')),
                ('enable_websocket', models.BooleanField(default=True, verbose_name='Bật WebSocket')),
                ('enable_tls', models.BooleanField(default=False, verbose_name='Bật TLS/SSL')),
                ('tls_cert_path', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn Certificate')),
                ('tls_key_path', models.CharField(blank=True, max_length=500, verbose_name='Đường dẫn Private Key')),
                ('max_connections', models.PositiveIntegerField(default=100, verbose_name='Số kết nối tối đa')),
                ('allow_anonymous', models.BooleanField(default=False, verbose_name='Cho phép ẩn danh')),
                ('enable_persistence', models.BooleanField(default=True, verbose_name='Bật lưu trữ (persistence)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Broker',
            },
        ),
        migrations.CreateModel(
            name='BrokerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('source', models.CharField(default='broker', max_length=50)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BrokerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Tên đăng nhập')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User MQTT',
                'verbose_name_plural': 'Users MQTT',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='BrokerACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_pattern', models.CharField(help_text='Ví dụ: fanjet/basement/#', max_length=500, verbose_name='Topic Pattern')),
                ('access_type', models.CharField(choices=[('read', 'Chỉ đọc (subscribe)'), ('write', 'Chỉ ghi (publish)'), ('readwrite', 'Đọc + Ghi'), ('deny', 'Từ chối')], default='readwrite', max_length=10, verbose_name='Quyền truy cập')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('user', models.ForeignKey(blank=True, help_text='Để trống = áp dụng cho tất cả', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acl_rules', to='mqtt_broker.brokeruser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'ACL Rule',
                'ordering': ['order', 'user__username'],
            },
        ),
    ]
